// Generated by CoffeeScript 1.6.3
angular.module('xbmcmagick').directive('onTap', function() {
  return function(scope, element, attrs) {
    return $(element).hammer({
      prevent_default: false,
      drag_vertical: false
    }).bind('tap', function() {
      return scope.$apply(attrs['onTap']);
    });
  };
});
