// Generated by CoffeeScript 1.6.3
var xbmcmagick;

xbmcmagick = angular.module('xbmcmagick');

xbmcmagick.factory('xbmcSettings', function($http, $rootScope) {
  var loadedSettings, localStorageKey, save, settings;
  localStorageKey = 'xbmcMagickSettings';
  settings = {
    address: '',
    port: '8080',
    auth: '',
    password: ''
  };
  loadedSettings = JSON.parse(localStorage.getItem(localStorageKey));
  loadedSettings || (loadedSettings = {});
  angular.extend(settings, loadedSettings);
  save = function() {
    return localStorage.setItem(localStorageKey, JSON.stringify(settings));
  };
  return {
    settings: settings,
    save: save
  };
});
