// Generated by CoffeeScript 1.6.2
var xbmcmagick;

xbmcmagick = angular.module('xbmcmagick');

xbmcmagick.factory('xbmcRemote', function($http, xbmcSettings, $rootScope) {
  var back, contextMenu, down, info, left, pause, play, right, select, sendAction, up;

  sendAction = function(action, extra) {
    var address, auth, data, port, protocol, req, settings, url;

    if (extra == null) {
      extra = {};
    }
    protocol = 'http';
    settings = xbmcSettings.settings;
    auth = settings.auth;
    if (auth.length > 0) {
      auth = "" + auth + "@";
    }
    address = settings.address;
    port = settings.port;
    url = "" + protocol + "://" + auth + address + ":" + port + "/jsonrpc";
    data = {
      "jsonrpc": "2.0",
      "method": action
    };
    angular.extend(data, extra);
    console.log("action -> " + action);
    console.log("data -> " + (JSON.stringify(data)));
    req = $.ajax({
      url: url,
      data: JSON.stringify(data),
      method: 'POST',
      dataType: 'json',
      headers: {
        'Content-Type': 'application/json; charset=utf-8'
      }
    });
    req.done(function(a) {
      console.log('done');
      return console.log(JSON.stringify(a));
    });
    return req.fail(function(a) {
      console.log('fail');
      return console.log(JSON.stringify(a));
    });
  };
  up = function() {
    return sendAction('Input.Up');
  };
  right = function() {
    return sendAction('Input.Right');
  };
  down = function() {
    return sendAction('Input.Down');
  };
  left = function() {
    return sendAction('Input.Left');
  };
  select = function() {
    return sendAction('Input.Select');
  };
  back = function() {
    return sendAction('Input.Back');
  };
  contextMenu = function() {
    sendAction('Input.ShowOSD');
    return sendAction('Input.ContextMenu');
  };
  play = function() {
    return sendAction('Player.PlayPause', {
      "Player.Id": 0
    });
  };
  pause = function() {
    return sendAction('Player.PlayPause', {
      "Player.Id": 0
    });
  };
  info = function() {
    return sendAction('Player.GetActivePlayer');
  };
  return {
    up: up,
    right: right,
    down: down,
    left: left,
    select: select,
    back: back,
    play: play,
    pause: pause,
    info: info,
    contextMenu: contextMenu
  };
});
