// Generated by CoffeeScript 1.6.2
var CommandsController;

CommandsController = function($scope, xbmcRemote) {
  $scope.play = xbmcRemote.play;
  $scope.pause = xbmcRemote.pause;
  return $scope.info = xbmcRemote.info;
};
