// Generated by CoffeeScript 1.6.2
var GestureController;

GestureController = function($scope, xbmcRemote) {
  var gestureTarget, hammeredGestureTarget, letter;

  letter = angular.element('#letter');
  letter[0].addEventListener('webkitAnimationEnd', function() {
    letter.removeClass('grow');
    return console.log('animationend');
  });
  gestureTarget = angular.element('#gesture-target');
  hammeredGestureTarget = gestureTarget.hammer();
  hammeredGestureTarget.on('swipeup', function() {
    letter.addClass('grow');
    return xbmcRemote.up();
  });
  hammeredGestureTarget.on('swiperight', function() {
    letter.addClass('grow');
    return xbmcRemote.right();
  });
  hammeredGestureTarget.on('swipedown', function() {
    letter.addClass('grow');
    return xbmcRemote.down();
  });
  hammeredGestureTarget.on('swipeleft', function() {
    letter.addClass('grow');
    return xbmcRemote.left();
  });
  gestureTarget.on('click', function() {
    letter.addClass('grow');
    return xbmcRemote.select();
  });
  hammeredGestureTarget.on('doubletap', function() {
    letter.addClass('grow');
    return xbmcRemote.back();
  });
  return hammeredGestureTarget.on('hold', function() {
    letter.addClass('grow');
    return xbmcRemote.contextMenu();
  });
};
